"""Data models for SRS Requirements, Pairs, LLM Predictions, and Evaluation Metrics."""

from enum import Enum
from typing import Any
from pydantic import BaseModel, Field, field_validator


class DependencyType(str, Enum):
    """Supported dependency types defined in paper Table I."""
    REQUIRES = "Requires"
    IMPLEMENTS = "Implements"
    CONFLICTS = "Conflicts"
    DETAILS = "Details"
    IS_SIMILAR = "Is similar"
    NO_DEPENDENCY = "No_dependency"

    @classmethod
    def normalize(cls, val: str) -> "DependencyType":
        """Normalize input string to standard DependencyType enum."""
        clean = val.strip().replace("_", " ").replace("-", " ").title()
        if "Require" in clean:
            return cls.REQUIRES
        elif "Implement" in clean:
            return cls.IMPLEMENTS
        elif "Conflict" in clean:
            return cls.CONFLICTS
        elif "Detail" in clean:
            return cls.DETAILS
        elif "Similar" in clean:
            return cls.IS_SIMILAR
        elif "No" in clean or "None" in clean or "Independent" in clean:
            return cls.NO_DEPENDENCY
        
        # Fallback exact string match
        for item in cls:
            if item.value.lower() == val.strip().lower():
                return item
        return cls.NO_DEPENDENCY


class Requirement(BaseModel):
    """Representation of an individual Software Requirement statement."""
    id: str = Field(..., description="Unique requirement ID (e.g. REQ-ADB-001)")
    text: str = Field(..., description="Natural language requirement statement text")
    system: str = Field(default="GenericSystem", description="System or subsystem name (e.g. ADB, TJA, APA)")
    source: str | None = Field(default=None, description="Source document or section reference")


class RequirementPair(BaseModel):
    """A pair of requirement statements evaluated for dependency."""
    id: str = Field(..., description="Unique requirement pair ID")
    req_a: Requirement = Field(..., description="First requirement statement (R1 / Requirement A)")
    req_b: Requirement = Field(..., description="Second requirement statement (R2 / Requirement B)")
    dependency_type: DependencyType | None = Field(
        default=None,
        description="Ground truth or annotated dependency type"
    )

    @field_validator("dependency_type", mode="before")
    @classmethod
    def parse_dependency_type(cls, v: Any) -> DependencyType | None:
        if v is None:
            return None
        if isinstance(v, DependencyType):
            return v
        if isinstance(v, str):
            return DependencyType.normalize(v)
        return None


class Prediction(BaseModel):
    """Output prediction generated by LEREDD detection engine."""
    pair_id: str = Field(..., description="Target requirement pair ID")
    dependency_type: DependencyType = Field(..., description="Predicted dependency type")
    rationale: str = Field(..., description="Detailed explanation/reasoning generated by LLM")
    confidence: int = Field(..., ge=0, le=5, description="Self-assessed Likert confidence score (0 to 5)")
    raw_response: str | None = Field(default=None, description="Raw unparsed output from LLM")
    prompt_tokens: int = Field(default=0, description="Tokens used for prompt")
    completion_tokens: int = Field(default=0, description="Tokens used for completion")
    estimated_cost_usd: float = Field(default=0.0, description="Estimated API cost in USD")


class EvaluationMetric(BaseModel):
    """Precision, Recall, F1 score and support for a single class or overall average."""
    precision: float = Field(..., description="Precision score [0.0, 1.0]")
    recall: float = Field(..., description="Recall score [0.0, 1.0]")
    f1_score: float = Field(..., description="F1 score [0.0, 1.0]")
    support: int = Field(..., description="Number of true instances")


class EvaluationReport(BaseModel):
    """Comprehensive evaluation summary matching Paper Tables III-IX structure."""
    system_name: str = Field(..., description="Dataset or evaluation system name (e.g. D1, D2, D3)")
    model_name: str = Field(..., description="Model/Strategy name evaluated")
    overall_accuracy: float = Field(..., description="Overall accuracy")
    macro_f1: float = Field(..., description="Macro average F1 score")
    weighted_f1: float = Field(..., description="Weighted average F1 score")
    per_class_metrics: dict[str, EvaluationMetric] = Field(..., description="Metrics for each dependency class")
    confusion_matrix: dict[str, dict[str, int]] | None = Field(
        default=None,
        description="Confusion matrix dictionary mapping ground_truth -> predicted -> count"
    )
